modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="more"
version="1.0.0.1"
displayName="MOre"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="LOG Drakon, MCreator"

[[dependencies.more]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




