modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="morematerials"
version="1.0.0"
displayName="MoreMaterials"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FABIEN, MCreator"

[[dependencies.morematerials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




